 update ast_grp set ast_grp_purchase_cost = '2400',ast_grp_rental_value = '35.87' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '15-093N' 
 update ast_grp set ast_grp_purchase_cost = '215000',ast_grp_rental_value = '3213.6' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-006N' 
 update ast_grp set ast_grp_purchase_cost = '76000',ast_grp_rental_value = '1135.97' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-004N' 
 update ast_grp set ast_grp_purchase_cost = '100800',ast_grp_rental_value = '1506.65' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-031N' 
 update ast_grp set ast_grp_purchase_cost = '99500',ast_grp_rental_value = '1487.22' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-008N' 
 update ast_grp set ast_grp_purchase_cost = '24800',ast_grp_rental_value = '370.68' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-009N' 
 update ast_grp set ast_grp_purchase_cost = '12800',ast_grp_rental_value = '191.32' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '17-483N' 
 update ast_grp set ast_grp_purchase_cost = '5200',ast_grp_rental_value = '77.72' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-011N' 
 update ast_grp set ast_grp_purchase_cost = '3300',ast_grp_rental_value = '49.32' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-010N' 
 update ast_grp set ast_grp_purchase_cost = '4800',ast_grp_rental_value = '71.74' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '10-228N' 
 update ast_grp set ast_grp_purchase_cost = '4150',ast_grp_rental_value = '62.03' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '12-956N' 
 update ast_grp set ast_grp_purchase_cost = '8900',ast_grp_rental_value = '133.02' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-012N' 
 update ast_grp set ast_grp_purchase_cost = '104000',ast_grp_rental_value = '1554.48' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '10-551N' 
 update ast_grp set ast_grp_purchase_cost = '4795',ast_grp_rental_value = '71.67' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '10-779N' 
 update ast_grp set ast_grp_purchase_cost = '17700',ast_grp_rental_value = '264.56' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '10-780N' 
 update ast_grp set ast_grp_purchase_cost = '6800',ast_grp_rental_value = '101.64' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-014N' 
 update ast_grp set ast_grp_purchase_cost = '14300',ast_grp_rental_value = '213.74' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '11-285N' 
 update ast_grp set ast_grp_purchase_cost = '3300',ast_grp_rental_value = '49.32' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '11-411N' 
 update ast_grp set ast_grp_purchase_cost = '4500',ast_grp_rental_value = '67.26' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '10-383N' 
 update ast_grp set ast_grp_purchase_cost = '16500',ast_grp_rental_value = '246.62' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '11-631N' 
 update ast_grp set ast_grp_purchase_cost = '9847',ast_grp_rental_value = '147.18' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-037N' 
 update ast_grp set ast_grp_purchase_cost = '9450',ast_grp_rental_value = '141.24' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-038N' 
 update ast_grp set ast_grp_purchase_cost = '12450',ast_grp_rental_value = '186.09' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-023N' 
 update ast_grp set ast_grp_purchase_cost = '12450',ast_grp_rental_value = '186.09' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-024N' 
 update ast_grp set ast_grp_purchase_cost = '5200',ast_grp_rental_value = '77.72' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '16-509N' 
 update ast_grp set ast_grp_purchase_cost = '33500',ast_grp_rental_value = '500.72' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '12-025N' 
 update ast_grp set ast_grp_purchase_cost = '1200',ast_grp_rental_value = '17.93' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '12-276N' 
 update ast_grp set ast_grp_purchase_cost = '4800',ast_grp_rental_value = '71.74' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '15-156N' 
 update ast_grp set ast_grp_purchase_cost = '7980',ast_grp_rental_value = '119.27' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '12-636N' 
 update ast_grp set ast_grp_purchase_cost = '2950',ast_grp_rental_value = '44.09' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '12-815N' 
 update ast_grp set ast_grp_purchase_cost = '1500',ast_grp_rental_value = '22.42' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '17-148N' 
 update ast_grp set ast_grp_purchase_cost = '17510',ast_grp_rental_value = '261.72' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-025N' 
 update ast_grp set ast_grp_purchase_cost = '6900',ast_grp_rental_value = '103.13' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-026N' 
 update ast_grp set ast_grp_purchase_cost = '25000',ast_grp_rental_value = '373.67' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-035N' 
 update ast_grp set ast_grp_purchase_cost = '20900',ast_grp_rental_value = '312.39' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-027N' 
 update ast_grp set ast_grp_purchase_cost = '9300',ast_grp_rental_value = '139' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-028N' 
 update ast_grp set ast_grp_purchase_cost = '1438',ast_grp_rental_value = '21.49' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '15-173N' 
 update ast_grp set ast_grp_purchase_cost = '1900',ast_grp_rental_value = '28.39' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '13-462N' 
 update ast_grp set ast_grp_purchase_cost = '61500',ast_grp_rental_value = '919.24' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-029N' 
 update ast_grp set ast_grp_purchase_cost = '34998',ast_grp_rental_value = '523.11' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-030N' 
 update ast_grp set ast_grp_purchase_cost = '2800',ast_grp_rental_value = '41.85' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '16-173N' 
 update ast_grp set ast_grp_purchase_cost = '8100',ast_grp_rental_value = '121.07' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '13-680N' 
 update ast_grp set ast_grp_purchase_cost = '20500',ast_grp_rental_value = '306.41' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '16-142N' 
 update ast_grp set ast_grp_purchase_cost = '6350',ast_grp_rental_value = '94.91' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '14-141N' 
 update ast_grp set ast_grp_purchase_cost = '4200',ast_grp_rental_value = '62.77' ,audit_user = 'Patch' , audit_date=getdate()  where audit_user = 'Patch' and ast_grp_grp_cd = '11-248N' 

 update ast_grp set ast_grp_purchase_cost = '9700',ast_grp_rental_value = '144.98' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '16-353N' 
 update ast_grp set ast_grp_purchase_cost = '29000',ast_grp_rental_value = '433.46' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-034N' 
 update ast_grp set ast_grp_purchase_cost = '2790',ast_grp_rental_value = '41.7' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-001N' 
 update ast_grp set ast_grp_purchase_cost = '129600',ast_grp_rental_value = '1937.13' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-032N' 
 update ast_grp set ast_grp_purchase_cost = '40000',ast_grp_rental_value = '597.88' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '11-165N' 
 update ast_grp set ast_grp_purchase_cost = '16500',ast_grp_rental_value = '246.62' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-035N' 
 update ast_grp set ast_grp_purchase_cost = '14300',ast_grp_rental_value = '213.74' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '16-412N' 
 update ast_grp set ast_grp_purchase_cost = '29000',ast_grp_rental_value = '433.46' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-008N' 
 update ast_grp set ast_grp_purchase_cost = '6290',ast_grp_rental_value = '94.01' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '11-283N' 
 update ast_grp set ast_grp_purchase_cost = '4950',ast_grp_rental_value = '73.98' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '11-490N' 
 update ast_grp set ast_grp_purchase_cost = '29000',ast_grp_rental_value = '433.46' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-009N' 
 update ast_grp set ast_grp_purchase_cost = '7800',ast_grp_rental_value = '116.58' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-013N' 
 update ast_grp set ast_grp_purchase_cost = '1900',ast_grp_rental_value = '28.39' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-036N' 
 update ast_grp set ast_grp_purchase_cost = '239000',ast_grp_rental_value = '3572.33' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '18-204N' 
 update ast_grp set ast_grp_purchase_cost = '21000',ast_grp_rental_value = '313.88' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-038N' 
 update ast_grp set ast_grp_purchase_cost = '110000',ast_grp_rental_value = '1644.17' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '12-539N' 
 update ast_grp set ast_grp_purchase_cost = '2770',ast_grp_rental_value = '41.4' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-045N' 
 update ast_grp set ast_grp_purchase_cost = '2000',ast_grp_rental_value = '29.89' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '15-786N' 
 update ast_grp set ast_grp_purchase_cost = '1700',ast_grp_rental_value = '25.41' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-039N' 
 update ast_grp set ast_grp_purchase_cost = '2460',ast_grp_rental_value = '36.77' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '99-901N' 
 update ast_grp set ast_grp_purchase_cost = '14500',ast_grp_rental_value = '216.73' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '13-269N' 
 update ast_grp set ast_grp_purchase_cost = '10819',ast_grp_rental_value = '161.71' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-025N' 
 update ast_grp set ast_grp_purchase_cost = '11750',ast_grp_rental_value = '175.62' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-041N' 
 update ast_grp set ast_grp_purchase_cost = '7700',ast_grp_rental_value = '115.09' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '99-900N' 
 update ast_grp set ast_grp_purchase_cost = '17500',ast_grp_rental_value = '261.57' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '13-746N' 
 update ast_grp set ast_grp_purchase_cost = '13350',ast_grp_rental_value = '199.54' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-031N' 
 update ast_grp set ast_grp_purchase_cost = '6490',ast_grp_rental_value = '97' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-042N' 
 update ast_grp set ast_grp_purchase_cost = '9800',ast_grp_rental_value = '146.48' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-028N' 
 update ast_grp set ast_grp_purchase_cost = '4500',ast_grp_rental_value = '67.26' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '99-902N' 
 update ast_grp set ast_grp_purchase_cost = '5202',ast_grp_rental_value = '77.75' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-043N' 
 update ast_grp set ast_grp_purchase_cost = '2500',ast_grp_rental_value = '37.36' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '14-263N' 
 update ast_grp set ast_grp_purchase_cost = '26000',ast_grp_rental_value = '388.62' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-044N' 
 update ast_grp set ast_grp_purchase_cost = '2050',ast_grp_rental_value = '30.64' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '14-369N' 
 update ast_grp set ast_grp_purchase_cost = '22950',ast_grp_rental_value = '343.03' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '14-413N' 
 update ast_grp set ast_grp_purchase_cost = '3300',ast_grp_rental_value = '49.32' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '15-612N' 
 update ast_grp set ast_grp_purchase_cost = '9500',ast_grp_rental_value = '141.99' ,audit_user = 'Patch' , audit_date=getdate()   where audit_user = 'Patch' and ast_grp_grp_cd = '17-465N' 

 update ast_grp set ast_grp_purchase_cost = '1280' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '10-082P' 
 update ast_grp set ast_grp_purchase_cost = '1250' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-005P' 
 update ast_grp set ast_grp_purchase_cost = '90' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '15-102P' 
 update ast_grp set ast_grp_purchase_cost = '2690' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '10-212P' 
 update ast_grp set ast_grp_purchase_cost = '3950' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '10-208P' 
 update ast_grp set ast_grp_purchase_cost = '1139' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '99-001P' 
 update ast_grp set ast_grp_purchase_cost = '1950' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '16-800P' 
 update ast_grp set ast_grp_purchase_cost = '1700' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '11-623P' 
 update ast_grp set ast_grp_purchase_cost = '350' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '11-696P' 
 update ast_grp set ast_grp_purchase_cost = '1470' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '15-076P' 
 update ast_grp set ast_grp_purchase_cost = '1250' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-037P' 
 update ast_grp set ast_grp_purchase_cost = '2000' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '12-351P' 
 update ast_grp set ast_grp_purchase_cost = '1500' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '12-278P' 
 update ast_grp set ast_grp_purchase_cost = '2600' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-034P' 
 update ast_grp set ast_grp_purchase_cost = '690' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '15-045P' 
 update ast_grp set ast_grp_purchase_cost = '1050' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '12-849P' 
 update ast_grp set ast_grp_purchase_cost = '2375' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-040P' 
 update ast_grp set ast_grp_purchase_cost = '390' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '13-367P' 
 update ast_grp set ast_grp_purchase_cost = '3200' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-022P' 
 update ast_grp set ast_grp_purchase_cost = '1850' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '18-458P' 
 update ast_grp set ast_grp_purchase_cost = '2000' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '18-457P' 
 update ast_grp set ast_grp_purchase_cost = '245' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '16-156P' 
 update ast_grp set ast_grp_purchase_cost = '68' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-020P' 
 update ast_grp set ast_grp_purchase_cost = '2250' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '13-775P' 
 update ast_grp set ast_grp_purchase_cost = '1250' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '13-187P' 
 update ast_grp set ast_grp_purchase_cost = '210' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = '17-888P' 
 update ast_grp set ast_grp_purchase_cost = '1524' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'ME-036P' 
 update ast_grp set ast_grp_purchase_cost = '936' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-046P' 
 update ast_grp set ast_grp_purchase_cost = '1900' ,audit_user = 'Patch' , audit_date=getdate() where audit_user = 'Patch' and ast_grp_grp_cd = 'DE-029P' 
