SELECT 
 replace(replace(replace(prm_mst_assetlocn			,char(9),''),char(10),''),char(13),'')						  	'District '
,replace(replace(replace(prm_mst_assetno			,char(9),''),char(10),''),char(13),'')						 	'BE Number '
,replace(replace(replace(prm_mst_closed_loop		,char(9),''),char(10),''),char(13),'')							 	'Closed Loop?'
,replace(replace(replace(prm_mst_create_by			,char(9),''),char(10),''),char(13),'')						 	'Created By:'
,replace(replace(replace(format(prm_mst_create_date,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')							 	'Created Date:'
,replace(replace(replace(prm_mst_curr_wo			,char(9),''),char(10),''),char(13),'')						 	'Current Work Order:'
,replace(replace(replace(prm_mst_desc		 		,char(9),''),char(10),''),char(13),'')						'Description:'
,replace(replace(replace(prm_mst_dflt_status		,char(9),''),char(10),''),char(13),'')							 	'Default WO Status:'
,replace(replace(replace(prm_mst_flt_code			,char(9),''),char(10),''),char(13),'')						 'Fault Code:'
,replace(replace(replace(prm_mst_freq_code			,char(9),''),char(10),''),char(13),'')						 	'Frequency Code:'
,replace(replace(replace(prm_mst_lead_day			,char(9),''),char(10),''),char(13),'')						 	'Lead Day:'
,replace(replace(replace(format(prm_mst_lpm_date,'dd/MM/yyyy hh:mm:ss')		 		,char(9),''),char(10),''),char(13),'')						'LPM Date:'
,replace(replace(replace(prm_mst_lpm_uom			,char(9),''),char(10),''),char(13),'')						 	'LPM UOM:'
,replace(replace(replace(prm_mst_lpm_usg			,char(9),''),char(10),''),char(13),'')						 	'LPM Usage:'
,replace(replace(replace(prm_mst_meter_id	 		,char(9),''),char(10),''),char(13),'')						'Meter ID:'
,replace(replace(replace(format(prm_mst_next_create,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')							 	'Next Create Date:'
,replace(replace(replace(format(prm_mst_next_due,'dd/MM/yyyy hh:mm:ss')				,char(9),''),char(10),''),char(13),'')						 	'Next Creation Due:'
,replace(replace(replace(format(prm_mst_override_date,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')							 	'Override Date:'
,replace(replace(replace(prm_mst_plan_priority		,char(9),''),char(10),''),char(13),'')							 	'Plan Priority:'
,replace(replace(replace(prm_mst_pm_grp				,char(9),''),char(10),''),char(13),'')						 	'PM Group:'
,replace(replace(replace(prm_mst_pm_no				,char(9),''),char(10),''),char(13),'')		 				'PM No:'
,replace(replace(replace(prm_mst_shadow_grp			,char(9),''),char(10),''),char(13),'')									 'Shadow Group:'
,replace(replace(replace(prm_mst_type		 		,char(9),''),char(10),''),char(13),'')						'PM Type:'
,replace(replace(replace(prm_det_act_code			,char(9),''),char(10),''),char(13),'')						 	'Action Code:'
,replace(replace(replace(prm_det_approver	 		,char(9),''),char(10),''),char(13),'')						'Approver:'
,replace(replace(replace(prm_det_asset_level		,char(9),''),char(10),''),char(13),'')							 	'State:'
,replace(replace(replace(prm_det_auto_replan		,char(9),''),char(10),''),char(13),'')							 	'Auto Replan:'
,replace(replace(replace(prm_det_c_account			,char(9),''),char(10),''),char(13),'')						  	'Contract Account:'
,replace(replace(replace(prm_det_cause_code			,char(9),''),char(10),''),char(13),'')						 	'Cause Code:'
,replace(replace(replace(prm_det_chg_costcenter		,char(9),''),char(10),''),char(13),'')							 	'Charge Cost Center:'
,replace(replace(replace(prm_det_crd_costcenter		,char(9),''),char(10),''),char(13),'')							 	'Credit Cost Center:'
,replace(replace(replace(prm_det_customer_cd		,char(9),''),char(10),''),char(13),'')							 	'Clinic Code:'
,replace(replace(replace(format(prm_det_datetime1	,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')						 	'Actual Planned Date:'
,replace(replace(replace(format(prm_det_datetime10	,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')						 'Date10:'
,replace(replace(replace(format(prm_det_datetime2	,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')						 	'Reschedule Date:'
,replace(replace(replace(format(prm_det_ent_date	,'dd/MM/yyyy hh:mm:ss')			,char(9),''),char(10),''),char(13),'')						 	'Ent Date:'
,replace(replace(replace(prm_det_freq_pct			,char(9),''),char(10),''),char(13),'')						 	'Frequency %:'
,replace(replace(replace(prm_det_l_account			,char(9),''),char(10),''),char(13),'')						 	'Labor Account:'
,replace(replace(replace(prm_det_m_account			,char(9),''),char(10),''),char(13),'')				 	'Material Account:'
,replace(replace(replace(prm_det_note1	 			,char(9),''),char(10),''),char(13),'')						'Clinic Name:'
,replace(replace(replace(prm_det_note2		 		,char(9),''),char(10),''),char(13),'')				'Note2:' 
,replace(replace(replace(prm_det_on_dispatch_q		,char(9),''),char(10),''),char(13),'')					 	'On Dispatch:'
,replace(replace(replace(prm_det_originator			,char(9),''),char(10),''),char(13),'')				 	'Originator:'
,replace(replace(replace(prm_det_planner	 		,char(9),''),char(10),''),char(13),'')				'Planner:'
,replace(replace(replace(prm_det_project_id			,char(9),''),char(10),''),char(13),'')				 	'Project ID:'
,replace(replace(replace(prm_det_safety		 		,char(9),''),char(10),''),char(13),'')				'Safety:'
,replace(replace(replace(prm_det_season		 		,char(9),''),char(10),''),char(13),'')				'Season:'
,replace(replace(replace(prm_det_season_beg			,char(9),''),char(10),''),char(13),'')				'Season Beg:'
,replace(replace(replace(prm_det_season_end			,char(9),''),char(10),''),char(13),'')				'Season End:'
,replace(replace(replace(format(prm_det_start_time,'dd/MM/yyyy hh:mm:ss')				,char(9),''),char(10),''),char(13),'')				'Start Time:'
,replace(replace(replace(prm_det_varchar1			,char(9),''),char(10),''),char(13),'')					'Clinic Type:'
,replace(replace(replace(prm_det_varchar2			,char(9),''),char(10),''),char(13),'')				 	'Clinic Category:'
,replace(replace(replace(prm_det_varchar20			,char(9),''),char(10),''),char(13),'')				'Varchar20:'
,replace(replace(replace(prm_det_varchar3			,char(9),''),char(10),''),char(13),'')				'Clinic Address:'
,replace(replace(replace(prm_det_varchar4			,char(9),''),char(10),''),char(13),'')				'Clinic Zone:'
,replace(replace(replace(prm_det_varchar5			,char(9),''),char(10),''),char(13),'')				'Manufacturer:'
,replace(replace(replace(prm_det_varchar6			,char(9),''),char(10),''),char(13),'')				'Model No:'
,replace(replace(replace(prm_det_varchar7			,char(9),''),char(10),''),char(13),'')				'Serial No:'
,replace(replace(replace(prm_det_varchar8			,char(9),''),char(10),''),char(13),'')				'Ownership:'
,replace(replace(replace(prm_det_varchar9			,char(9),''),char(10),''),char(13),'')				'Clinic Contact:'
,replace(replace(replace(prm_det_work_area			,char(9),''),char(10),''),char(13),'')				'Circle:'
,replace(replace(replace(prm_det_work_class			,char(9),''),char(10),''),char(13),'')				'SM Type:'
,replace(replace(replace(prm_det_work_grp			,char(9),''),char(10),''),char(13),'')				'Work Group:'
,replace(replace(replace(prm_det_work_locn			,char(9),''),char(10),''),char(13),'')				'Work Location:'
,replace(replace(replace(prm_det_work_type			,char(9),''),char(10),''),char(13),'')				'Work Type:'


from prm_mst m (nolock)
join prm_det d (nolock)
on m.RowID = d.mst_RowID

--SELECT * from cf_label where table_name = 'prm_det' and language_cd = 'DEFAULT'