SELECT 
prm_mst_assetlocn		  	'District '
,prm_mst_assetno		 	'BE Number '
,prm_mst_closed_loop		 	'Closed Loop?'
,prm_mst_create_by		 	'Created By:'
,prm_mst_create_date		 	'Created Date:'
,prm_mst_curr_wo		 	'Current Work Order:'
,prm_mst_desc		 	'Description:'
,prm_mst_dflt_status		 	'Default WO Status:'
,prm_mst_flt_code		 'Fault Code:'
,prm_mst_freq_code		 	'Frequency Code:'
,prm_mst_lead_day		 	'Lead Day:'
,prm_mst_lpm_date	 	'LPM Date:'
,prm_mst_lpm_uom		 	'LPM UOM:'
,prm_mst_lpm_usg		 	'LPM Usage:'
,prm_mst_meter_id	 	'Meter ID:'
,prm_mst_next_create		 	'Next Create Date:'
,prm_mst_next_due		 	'Next Creation Due:'
,prm_mst_override_date		 	'Override Date:'
,prm_mst_plan_priority		 	'Plan Priority:'
,prm_mst_pm_grp		 	'PM Group:'
,prm_mst_pm_no	 	'PM No:'
,prm_mst_shadow_grp		 'Shadow Group:'
,prm_mst_type		 	'PM Type:'

,prm_det_act_code		 	'Action Code:'
,prm_det_approver	 	'Approver:'
,prm_det_asset_level		 	'State:'
,prm_det_auto_replan		 	'Auto Replan:'
,prm_det_c_account		  	'Contract Account:'
,prm_det_cause_code		 	'Cause Code:'
,prm_det_chg_costcenter		 	'Charge Cost Center:'
,prm_det_crd_costcenter		 	'Credit Cost Center:'
,prm_det_customer_cd		 	'Clinic Code:'
,prm_det_datetime1		 	'Actual Planned Date:'
,prm_det_datetime10		 'Date10:'
,prm_det_datetime2		 	'Reschedule Date:'
 
,prm_det_ent_date		 	'Ent Date:'
,prm_det_freq_pct		 	'Frequency %:'
,prm_det_l_account		 	'Labor Account:'
,prm_det_m_account	 	'Material Account:'
,prm_det_note1	 	'Clinic Name:'
,prm_det_note2		 	'Note2:' 
,prm_det_on_dispatch_q		 	'On Dispatch:'
,prm_det_originator		 	'Originator:'
,prm_det_planner	 	'Planner:'
,prm_det_project_id		 	'Project ID:'
,prm_det_safety		 	'Safety:'
,prm_det_season		 	'Season:'
,prm_det_season_beg		'Season Beg:'
,prm_det_season_end		'Season End:'
,prm_det_start_time		'Start Time:'
,prm_det_varchar1			'Clinic Type:'
 
,prm_det_varchar2		 	'Clinic Category:'
,prm_det_varchar20		'Varchar20:'
,prm_det_varchar3		'Clinic Address:'
,prm_det_varchar4		'Clinic Zone:'
,prm_det_varchar5		'Manufacturer:'
,prm_det_varchar6		'Model No:'
,prm_det_varchar7		'Serial No:'
,prm_det_varchar8		'Ownership:'
,prm_det_varchar9		'Clinic Contact:'
,prm_det_work_area		'Circle:'
,prm_det_work_class		'SM Type:'
,prm_det_work_grp		'Work Group:'
,prm_det_work_locn		'Work Location:'
,prm_det_work_type		'Work Type:'


from prm_mst m (nolock)
join prm_det d (nolock)
on m.RowID = d.mst_RowID

--SELECT * from cf_label where table_name = 'prm_det' and language_cd = 'DEFAULT'